name: pylint

on:
  push:
    branches: [ main, develop, ms/initial_state_index ]
  pull_request:
    branches: [ main, develop ]

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install dependencies
        run: |
          pip install pylint
          pip install -r requirements.txt
      - name: Lint
        run: pylint src/